name: marp-to-pages
on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Ensure build dir exists
      run: mkdir -p build

    - name: Copy images and assets to build
      run: |
        cp -R *.jpeg build/ 2>/dev/null || true
        cp -R *.jpg build/ 2>/dev/null || true  
        cp -R *.png build/ 2>/dev/null || true
        cp -R *.css build/ 2>/dev/null || true

    - name: Marp Build (presentation.html)
      uses: docker://marpteam/marp-cli:v3.4.0
      with:
        args: presentation.md --theme rose-pine-dawn.css -o build/index.html
      env:
        MARP_USER: root:root

    - name: Marp Build (presentation.pdf)  
      uses: docker://marpteam/marp-cli:v3.4.0
      with:
        args: presentation.md --theme rose-pine-dawn.css -o build/presentation.pdf
      env:
        MARP_USER: root:root

    - name: Deploy to GitHub Pages
      if: github.event_name != 'pull_request'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        enable_jekyll: false
